In [1]:
cd ..

/home/abhishekabhishek/git/UnsupGenModbyMPS


In [39]:
import pennylane as qml
import numpy as np
from pennylane import numpy as pnp

In [24]:
shots = None
dev = qml.device('default.qubit', wires=2, shots=shots)

In [85]:
@qml.qnode(dev)
def circuit():
    
    if shots is not None:
        return qml.sample()
    
    return qml.probs(wires=[0, 1])

In [87]:
probs = circuit()
probs

tensor([1., 0., 0., 0.], requires_grad=True)

In [90]:
idxs = pnp.tensor([1, 2], requires_grad=False)

In [91]:
probs[idxs]

tensor([0., 0.], requires_grad=True)

In [78]:
len(probs)

1

In [79]:
p_data = pnp.tensor(1./2, requires_grad=False)

In [80]:
pnp.log(p_data)

tensor(-0.69314718, requires_grad=False)

In [81]:
pnp.log(probs)

tensor([0.], requires_grad=True)

In [82]:
log_p_over_q = pnp.log(probs) - pnp.log(p_data)
log_p_over_q

tensor([0.69314718], requires_grad=True)

In [83]:
pnp.dot(probs, log_p_over_q)

0.6931471805599453

In [84]:
np.log(0.5)

-0.6931471805599453

In [96]:
data = np.load('BStest/BSdata.npy')
print(data.shape)
data.dtype

(30, 4, 4)


dtype('bool')

In [97]:
data = data.reshape(-1, data.shape[1]*data.shape[2])
data.shape

(30, 16)

In [102]:
data = data.astype(np.int32)
data.shape

(30, 16)

In [111]:
data.dtype

dtype('int32')

In [103]:
data.dot(2**np.arange(data.size)[::-1])

ValueError: shapes (30,16) and (480,) not aligned: 16 (dim 1) != 480 (dim 0)

Now that we have an implementation for the KL-divergence, let's run that on the 

In [108]:
b = np.array([1,0,1,0,0,0,0,0,1,0,1])
data_bin = np.dot(data, 2**np.arange(data.shape[1])[::-1])

In [109]:
data_bin.shape

(30,)

In [110]:
data_bin

array([    0, 65535, 61440, 34952,  3840, 17476, 65280, 52428,   240,
        8738, 61680, 43690,  4080, 26214, 65520, 61166,    15,  4369,
       61455, 39321,  3855, 21845, 65295, 56797,   255, 13107, 61695,
       48059,  4095, 30583])